[tools]
dotnet = "10.0.102"
node = "25.6.0"
"npm:@angular/cli" = "21.1.3"
"npm:@angular/language-server" = "21.1.3"
"npm:eslint_d" = "14.3.0"
"npm:oxlint" = "1.46.0"
"npm:typescript-language-server" = "5.1.3"
prettier = "3.7.4"
